'use strict';
const $=s=>document.querySelector(s), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmtDate=v=>v?new Date(v).toLocaleString([], {dateStyle:'medium',timeStyle:'short'}):'—';
const money=(v,c='USD')=>new Intl.NumberFormat(undefined,{style:'currency',currency:c||'USD',maximumFractionDigits:0}).format(+v||0);
const CONFIG=window.THERMO_CRM_CONFIG||{}, API_BASE=String(CONFIG.apiBaseUrl||'').replace(/\/$/,'');
const cognitoEnabled=Boolean(CONFIG.region&&CONFIG.userPoolId&&CONFIG.clientId&&API_BASE);
let token=sessionStorage.getItem('thermoCrmAccessToken')||'', refreshToken=sessionStorage.getItem('thermoCrmRefreshToken')||'', current='dashboard', cache={contacts:[],companies:[],deals:[],tasks:[]}, challengeSession='';
const NAV=[['WORKSPACE',[['dashboard','Dashboard'],['today','Today'],['week','This week'],['calendar','Calendar']]],['RECORDS',[['contacts','Contacts'],['companies','Companies'],['deals','Deals'],['pipeline','Pipeline']]],['WORK',[['tasks','Tasks'],['submissions','Submissions'],['emails','Emails'],['sent','Sent emails'],['compose','Compose']]],['ADMIN',[['audit','Audit log'],['settings','Settings']]]];
const META={dashboard:['WORKSPACE','Dashboard'],today:['WORKSPACE','Today'],week:['WORKSPACE','This week'],calendar:['WORKSPACE','Calendar'],contacts:['RECORDS','Contacts'],companies:['RECORDS','Companies'],deals:['RECORDS','Deals'],pipeline:['RECORDS','Pipeline'],tasks:['WORK','Tasks'],submissions:['WORK','Form submissions'],emails:['WORK','Emails'],sent:['WORK','Sent emails'],compose:['WORK','Compose'],audit:['ADMIN','Audit log'],settings:['ADMIN','Settings']};
const api=async(path,opt={})=>{const r=await fetch(`${API_BASE}${path}`,{...opt,headers:{Authorization:`Bearer ${token}`,...(opt.body?{'Content-Type':'application/json'}:{}),...(opt.headers||{})}});if(!r.ok){let e={};try{e=await r.json()}catch{};throw new Error(e.error||`Request failed (${r.status})`)}return r.headers.get('content-type')?.includes('json')?r.json():r};
async function cognito(target,payload){const r=await fetch(`https://cognito-idp.${CONFIG.region}.amazonaws.com/`,{method:'POST',headers:{'Content-Type':'application/x-amz-json-1.1','X-Amz-Target':`AWSCognitoIdentityProviderService.${target}`},body:JSON.stringify(payload)});const data=await r.json();if(!r.ok)throw new Error(data.message||data.__type||'Sign-in failed.');return data}
async function localSignIn(email,password){const r=await fetch(`${API_BASE}/api/login`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({email,password})});const data=await r.json();if(!r.ok)throw new Error(data.error||'Sign-in failed.');token=data.accessToken||'';if(!token)throw new Error('The server did not return a session.');sessionStorage.setItem('thermoCrmAccessToken',token)}
async function signIn(username,password,newPassword=''){let data;if(challengeSession&&newPassword){data=await cognito('RespondToAuthChallenge',{ClientId:CONFIG.clientId,ChallengeName:'NEW_PASSWORD_REQUIRED',Session:challengeSession,ChallengeResponses:{USERNAME:username,NEW_PASSWORD:newPassword}})}else{data=await cognito('InitiateAuth',{ClientId:CONFIG.clientId,AuthFlow:'USER_PASSWORD_AUTH',AuthParameters:{USERNAME:username,PASSWORD:password}})}if(data.ChallengeName==='NEW_PASSWORD_REQUIRED'){challengeSession=data.Session;$('#new-password-wrap').classList.remove('hidden');$('#new-password').required=true;throw new Error('Please set a new password to finish your first sign-in.')}const auth=data.AuthenticationResult||{};token=auth.AccessToken||auth.IdToken||'';refreshToken=auth.RefreshToken||'';if(!token)throw new Error('Cognito did not return an access token.');sessionStorage.setItem('thermoCrmAccessToken',token);if(refreshToken)sessionStorage.setItem('thermoCrmRefreshToken',refreshToken)}
function toast(text){const n=$('#toast');n.textContent=text;n.classList.remove('hidden');setTimeout(()=>n.classList.add('hidden'),2600)}
function pill(value){return `<span class="pill ${esc(value)}">${esc(String(value||'—').replaceAll('_',' '))}</span>`}
function empty(label='No records yet'){return `<div class="empty"><b>${label}</b><p>Add a record when there is real information to manage.</p></div>`}
function openDrawer(html){$('#drawer').innerHTML=html;$('#drawer-backdrop').classList.remove('hidden')}
function closeDrawer(){$('#drawer-backdrop').classList.add('hidden')}
function nav(){return NAV.map(([group,links])=>`<p class="nav-group">${group}</p>${links.map(([id,label])=>`<button class="nav-item" data-route="${id}">${label}</button>`).join('')}`).join('')}
async function route(id=current){current=id;location.hash=id;const [crumb,title]=META[id]||META.dashboard;$('#crumb').textContent=crumb;$('#title').textContent=title;document.querySelectorAll('.nav-item').forEach(x=>x.classList.toggle('active',x.dataset.route===id));$('#view').innerHTML='<div class="empty">Loading…</div>';try{await RENDER[id]()}catch(e){$('#view').innerHTML=`<div class="notice"><b>Unable to load this view</b><br>${esc(e.message)}</div>`}}
function rowsTable(cols,rows,onClick){if(!rows.length)return empty();return `<div class="table-wrap"><table><thead><tr>${cols.map(c=>`<th>${c[0]}</th>`).join('')}</tr></thead><tbody>${rows.map(row=>`<tr class="${onClick?'clickable':''}" data-id="${row.id}">${cols.map(c=>`<td>${typeof c[1]==='function'?c[1](row):esc(row[c[1]]||'—')}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
function bindRows(fn){document.querySelectorAll('tbody tr[data-id]').forEach(r=>r.onclick=()=>fn(r.dataset.id))}

async function dashboard(){const d=await api('/api/dashboard');const c=d.counts;$('#view').innerHTML=`<div class="metrics">${[['New submissions',c.new_submissions],['Open tasks',c.open_tasks],['Active deals',c.active_deals],['Pipeline value',money(c.pipeline_value)]].map(x=>`<div class="metric"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('')}</div><div class="grid"><section class="card"><div class="card-head"><h2>Recent submissions</h2><button class="secondary" data-go="submissions">View all</button></div>${list(d.recent_submissions,x=>`<b>${esc(x.name)}</b><small>${esc(x.inquiry_type)} · ${fmtDate(x.created_at)}</small>`,x=>pill(x.status))}</section><section class="card"><div class="card-head"><h2>Upcoming work</h2><button class="secondary" data-go="tasks">View tasks</button></div>${list(d.upcoming_tasks,x=>`<b>${esc(x.title)}</b><small>${fmtDate(x.due_at)} · ${esc(x.assignee||'Unassigned')}</small>`,x=>pill(x.priority))}</section><section class="card"><h2>Largest active deals</h2>${list(d.top_deals,x=>`<b>${esc(x.name)}</b><small>${esc(x.stage_id)}</small>`,x=>money(x.amount,x.currency))}</section><section class="card"><h2>Workspace health</h2><div class="metrics" style="grid-template-columns:1fr 1fr;margin:0"><div class="metric"><small>Contacts</small><strong>${c.contacts}</strong></div><div class="metric"><small>Due today</small><strong>${c.due_today}</strong></div></div></section></div>`;bindGo()}
function list(data,left,right){return data.length?`<div class="list">${data.map(x=>`<div class="list-row"><div>${left(x)}</div><div>${right(x)}</div></div>`).join('')}</div>`:empty()}
function bindGo(){document.querySelectorAll('[data-go]').forEach(x=>x.onclick=()=>route(x.dataset.go))}

async function taskView(mode){const data=await api('/api/tasks');cache.tasks=data.items;const now=new Date(),today=now.toISOString().slice(0,10),end=new Date(now);end.setDate(now.getDate()+7);const endDay=end.toISOString().slice(0,10);let rows=data.items;if(mode==='today')rows=rows.filter(x=>x.due_at.slice(0,10)===today);if(mode==='week')rows=rows.filter(x=>x.due_at&&x.due_at.slice(0,10)>=today&&x.due_at.slice(0,10)<=endDay);$('#view').innerHTML=`<div class="page-actions"><h2>${mode==='today'?"Today's work":mode==='week'?'Next seven days':'All tasks'}</h2><button class="primary" id="add-task">＋ Task</button></div>${rowsTable([['Task','title'],['Due',x=>fmtDate(x.due_at)],['Priority',x=>pill(x.priority)],['Assignee','assignee'],['Status',x=>pill(x.status)]],rows,true)}`;$('#add-task').onclick=()=>resourceForm('tasks');bindRows(id=>resourceForm('tasks',data.items.find(x=>x.id===id)))}
async function calendar(){const data=await api('/api/calendar'),now=new Date(),year=now.getFullYear(),month=now.getMonth(),first=new Date(year,month,1),start=new Date(year,month,1-first.getDay()),days=[];for(let i=0;i<42;i++){const date=new Date(start);date.setDate(start.getDate()+i);const key=date.toISOString().slice(0,10),events=data.items.filter(x=>x.due_at.slice(0,10)===key);days.push(`<div class="day ${date.getMonth()!==month?'out':''}"><span class="date">${date.getDate()}</span>${events.slice(0,3).map(x=>`<div class="event">${esc(x.title)}</div>`).join('')}</div>`)}$('#view').innerHTML=`<div class="page-actions"><h2>${now.toLocaleString([],{month:'long',year:'numeric'})}</h2><button class="primary" id="add-task">＋ Event / task</button></div><div class="calendar-grid">${days.join('')}</div>`;$('#add-task').onclick=()=>resourceForm('tasks')}

const DEFINITIONS={contacts:{title:'Contact',fields:[['name','Name','text',true],['email','Email','email'],['phone','Phone'],['title','Job title'],['company_id','Company','select:companies'],['source','Source'],['region','Region'],['owner','Owner'],['last_interaction','Last interaction','datetime-local'],['notes','Notes','textarea']]},companies:{title:'Company',fields:[['name','Company name','text',true],['website','Website','url'],['industry','Industry'],['region','Region'],['address','Address'],['owner','Owner'],['notes','Notes','textarea']]},deals:{title:'Deal',fields:[['name','Deal name','text',true],['company_id','Company','select:companies'],['contact_id','Contact','select:contacts'],['amount','Amount','number'],['currency','Currency','select:currency'],['stage_id','Stage','select:stage'],['probability','Probability %','number'],['close_date','Expected close','date'],['owner','Owner'],['notes','Notes','textarea']]},tasks:{title:'Task',fields:[['title','Title','text',true],['task_type','Type','select:tasktype'],['priority','Priority','select:priority'],['due_at','Due','datetime-local'],['status','Status','select:taskstatus'],['assignee','Assignee'],['related_type','Related record type'],['related_id','Related record ID'],['notes','Notes','textarea']]},emails:{title:'Email',fields:[['recipient','To','email',true],['subject','Subject','text',true],['body','Message','textarea'],['status','Delivery','hidden'],['related_type','Related record type'],['related_id','Related record ID']]}};
const options={currency:[['USD','USD'],['TWD','TWD'],['EUR','EUR']],stage:[['new','New lead'],['qualified','Qualified'],['proposal','Proposal'],['negotiation','Negotiation'],['won','Won'],['lost','Lost']],tasktype:[['follow_up','Follow-up'],['call','Call'],['meeting','Meeting'],['email','Email'],['other','Other']],priority:[['low','Low'],['normal','Normal'],['high','High']],taskstatus:[['open','Open'],['in_progress','In progress'],['done','Done'],['cancelled','Cancelled']]};
async function preload(){const [a,b]=await Promise.all([api('/api/companies'),api('/api/contacts')]);cache.companies=a.items;cache.contacts=b.items}
function fieldHTML([name,label,type='text',required],record){let value=record?.[name]??'';if(type==='hidden')return `<input type="hidden" name="${name}" value="${esc(value)}">`;if(type==='textarea')return `<label class="wide">${label}<textarea name="${name}" ${required?'required':''}>${esc(value)}</textarea></label>`;if(type.startsWith('select:')){const key=type.split(':')[1];let opts=options[key]||[];if(key==='companies')opts=cache.companies.map(x=>[x.id,x.name]);if(key==='contacts')opts=cache.contacts.map(x=>[x.id,x.name]);return `<label>${label}<select name="${name}" ${required?'required':''}><option value="">Select…</option>${opts.map(o=>`<option value="${esc(o[0])}" ${o[0]===String(value)?'selected':''}>${esc(o[1])}</option>`).join('')}</select></label>`}return `<label>${label}<input name="${name}" type="${type}" value="${esc(value)}" ${required?'required':''}></label>`}
async function resourceForm(resource,record=null,defaults={}){await preload();record={...defaults,...(record||{})};const def=DEFINITIONS[resource];openDrawer(`<div class="drawer-head"><h2>${record.id?'Edit':'New'} ${def.title}</h2><button class="icon close">✕</button></div>${resource==='emails'?'<p class="notice">Local queue only. Saving this message does not send an email.</p>':''}<form id="resource-form"><div class="form-grid">${def.fields.map(f=>fieldHTML(f,record)).join('')}</div><div class="form-actions">${record.id?'<button type="button" class="danger" id="delete-record">Delete</button>':''}<button type="button" class="secondary close">Cancel</button><button class="primary">${resource==='emails'?'Add to queue':'Save'}</button></div></form>`);document.querySelectorAll('.close').forEach(x=>x.onclick=closeDrawer);$('#resource-form').onsubmit=async e=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.target));if(resource==='emails')body.status='queued';await api(`/api/${resource}${record.id?'/'+record.id:''}`,{method:record.id?'PATCH':'POST',body:JSON.stringify(body)});closeDrawer();toast('Saved');route(current)};if(record.id)$('#delete-record').onclick=async()=>{if(!confirm(`Delete this ${def.title.toLowerCase()}?`))return;await api(`/api/${resource}/${record.id}`,{method:'DELETE'});closeDrawer();toast('Deleted');route(current)}}

async function resourceList(resource){const d=await api(`/api/${resource}`);cache[resource]=d.items;const config={contacts:[['Name','name'],['Email','email'],['Region','region'],['Owner','owner'],['Last interaction',x=>fmtDate(x.last_interaction)]],companies:[['Company','name'],['Industry','industry'],['Region','region'],['Owner','owner'],['Website','website']],deals:[['Deal','name'],['Value',x=>money(x.amount,x.currency)],['Stage',x=>pill(x.stage_id)],['Probability',x=>`${x.probability}%`],['Close date','close_date']]}[resource];$('#view').innerHTML=`<div class="page-actions"><h2>${d.total} ${resource}</h2><button class="primary" id="add-resource">＋ ${DEFINITIONS[resource].title}</button></div>${rowsTable(config,d.items,true)}`;$('#add-resource').onclick=()=>resourceForm(resource);bindRows(id=>resourceForm(resource,d.items.find(x=>x.id===id)))}

async function pipeline(){const d=await api('/api/pipeline');$('#view').innerHTML=`<div class="page-actions"><h2>Sales pipeline</h2><button class="primary" id="add-deal">＋ Deal</button></div><div class="pipeline">${d.stages.map(s=>{const deals=d.deals.filter(x=>x.stage_id===s.id);return `<section class="stage"><div class="stage-head"><b>${esc(s.name)}</b><span>${deals.length}</span></div><small>${money(deals.reduce((a,x)=>a+(+x.amount||0),0))}</small><div style="margin-top:13px">${deals.map(x=>`<article class="deal-card" data-id="${x.id}"><b>${esc(x.name)}</b><span>${money(x.amount,x.currency)}</span><small>${esc(x.company_name||'No company')} · ${x.probability}%</small></article>`).join('')}</div></section>`}).join('')}</div>`;$('#add-deal').onclick=()=>resourceForm('deals');document.querySelectorAll('.deal-card').forEach(x=>x.onclick=()=>resourceForm('deals',d.deals.find(y=>y.id===x.dataset.id)))}

const palette=['#6e7d91','#4dbbe4','#f5787e','#43cea0','#f7b733','#8b79d1'];
function donut(data){if(!data.length)return empty('No submission data');const total=data.reduce((a,x)=>a+x.value,0);let at=0,parts=data.map((x,i)=>{const from=at;at+=x.value/total*100;return `${palette[i%palette.length]} ${from}% ${at}%`});return `<div class="donut-wrap"><div class="donut" style="background:conic-gradient(${parts.join(',')})"></div><div class="legend">${data.slice(0,6).map((x,i)=>`<div><i class="dot" style="background:${palette[i%palette.length]}"></i><span>${esc(x.label)} <b>${x.value}</b></span></div>`).join('')}</div></div>`}
function bars(data){if(!data.length)return empty('No monthly data');const max=Math.max(...data.map(x=>x.value),1);return `<div class="chart">${data.map(x=>`<div class="bar-wrap" title="${esc(x.label)}: ${x.value}"><div class="bar" style="height:${Math.max(3,x.value/max*100)}%"></div><span class="bar-label">${esc(x.label.slice(5))}</span></div>`).join('')}</div>`}
async function submissions(){const [data,stats]=await Promise.all([api('/api/submissions'),api('/api/submission-stats')]);const regions=[...new Set(data.items.map(x=>x.region).filter(Boolean))],types=[...new Set(data.items.map(x=>x.inquiry_type).filter(Boolean))];$('#view').innerHTML=`<div class="grid three"><section class="card"><h2>Region breakdown</h2>${donut(stats.region)}<p class="muted">${stats.total} valid submissions</p></section><section class="card"><h2>Lead source</h2>${donut(stats.source)}</section><section class="card"><h2>Monthly submissions</h2>${bars(stats.months)}</section></div><div style="height:22px"></div><div class="filters"><input id="sub-q" placeholder="Search name, email, company or message"><select id="sub-status"><option value="">All statuses</option>${['new','in_review','contacted','qualified','closed'].map(x=>`<option>${x}</option>`).join('')}</select><select id="sub-region"><option value="">All regions</option>${regions.map(x=>`<option>${esc(x)}</option>`).join('')}</select><select id="sub-type"><option value="">All forms</option>${types.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join('')}</select><select id="sub-spam"><option value="">All messages</option><option value="0">Valid only</option><option value="1">Spam only</option></select><select id="sub-sort"><option value="">Newest first</option><option value="oldest">Oldest first</option><option value="name">Name</option><option value="status">Status</option></select><button class="secondary" id="export-sub">Export CSV</button></div><div id="sub-table"></div>`;
  const paint=items=>{const table=$('#sub-table');table.innerHTML=rowsTable([['Time',x=>fmtDate(x.created_at)],['Region',x=>pill(x.region)],['Form','inquiry_type'],['Name',x=>`<b>${esc(x.name)}</b><small>${esc(x.email)}</small>`],['Company','organization'],['Status',x=>x.is_spam?pill('spam'):pill(x.status)],['Assignee','assignee']],items,true);bindRows(id=>submissionDetail(items.find(x=>x.id===id)))};paint(data.items);
  async function filter(){const p=new URLSearchParams({q:$('#sub-q').value,status:$('#sub-status').value,region:$('#sub-region').value,type:$('#sub-type').value,spam:$('#sub-spam').value,sort:$('#sub-sort').value});const d=await api('/api/submissions?'+p);paint(d.items)}
  document.querySelectorAll('.filters input,.filters select').forEach(x=>x.oninput=filter);$('#export-sub').onclick=async()=>{const r=await api('/api/submissions.csv');const a=document.createElement('a');a.href=URL.createObjectURL(await r.blob());a.download='thermoverse-submissions.csv';a.click()}}
function submissionDetail(x){const details=[['Received',fmtDate(x.created_at)],['Email',x.email],['Company',x.organization],['Role',x.role],['Region',x.region],['Form',x.inquiry_type],['Source',x.source],['Language',x.language],['Message',x.message],['Site type',x.site_type],['Location',x.location],['Site description',x.site_description],['Current challenge',x.current_problem],['Available data',x.data_available],['Preferred contact time',x.contact_time]].filter(y=>y[1]);openDrawer(`<div class="drawer-head"><div><p class="eyebrow">SUBMISSION</p><h2>${esc(x.name)}</h2></div><button class="icon close">✕</button></div><div class="form-grid"><label>Status<select id="detail-status">${['new','in_review','contacted','qualified','closed'].map(v=>`<option value="${v}" ${v===x.status?'selected':''}>${v.replace('_',' ')}</option>`).join('')}</select></label><label>Assignee<input id="detail-assignee" value="${esc(x.assignee)}"></label><label>Region<input id="detail-region" value="${esc(x.region)}"></label><label style="display:flex;align-items:center;gap:8px;margin-top:25px"><input id="detail-spam" type="checkbox" ${x.is_spam?'checked':''}> Mark as spam</label><label class="wide">Internal notes<textarea id="detail-note">${esc(x.internal_note)}</textarea></label></div><div class="form-actions"><button class="secondary" id="convert-sub" ${x.converted_contact_id?'disabled':''}>${x.converted_contact_id?'Converted':'Convert to contact / company'}</button><button class="primary" id="save-sub">Save changes</button></div><hr style="border:0;border-top:1px solid var(--line);margin:25px 0"><dl class="detail-grid">${details.map(d=>`<dt>${d[0]}</dt><dd>${esc(d[1])}</dd>`).join('')}</dl>`);document.querySelectorAll('.close').forEach(n=>n.onclick=closeDrawer);$('#save-sub').onclick=async()=>{await api(`/api/submissions/${x.id}`,{method:'PATCH',body:JSON.stringify({status:$('#detail-status').value,assignee:$('#detail-assignee').value,region:$('#detail-region').value,isSpam:$('#detail-spam').checked,internalNote:$('#detail-note').value})});closeDrawer();toast('Submission updated');submissions()};$('#convert-sub').onclick=async()=>{await api(`/api/submissions/${x.id}/convert`,{method:'POST',body:JSON.stringify({createContact:true,createCompany:true})});closeDrawer();toast('Contact and company created');submissions()}}

async function emails(mode='all'){const d=await api('/api/emails');let records=d.items;if(mode==='sent')records=records.filter(x=>x.status==='sent');$('#view').innerHTML=`<div class="page-actions"><h2>${records.length} ${mode==='sent'?'sent':'saved'} emails</h2><button class="primary" id="compose-email">＋ Compose</button></div>${mode==='all'?'<p class="notice">Messages are queued unless Amazon SES delivery was explicitly enabled during deployment.</p><br>':''}${rowsTable([['Created',x=>fmtDate(x.created_at)],['Recipient','recipient'],['Subject','subject'],['Status',x=>pill(x.status)],['Sent',x=>fmtDate(x.sent_at)]],records,true)}`;$('#compose-email').onclick=()=>resourceForm('emails',null,{status:'queued'});bindRows(id=>resourceForm('emails',records.find(x=>x.id===id)))}
async function auditView(){const d=await api('/api/audit');$('#view').innerHTML=rowsTable([['Time',x=>fmtDate(x.created_at)],['Actor','actor'],['Action',x=>pill(x.action)],['Record',x=>`${esc(x.target_type)}<small>${esc(x.target_id)}</small>`],['Summary','summary']],d.items)}
async function settings(){const d=await api('/api/settings'),s=d.settings;$('#view').innerHTML=`<div class="grid"><section class="card"><h2>Workspace</h2><form id="settings-form"><div class="form-grid"><label>Workspace name<input name="workspace_name" value="${esc(s.workspace_name)}"></label><label>Default currency<select name="default_currency">${['USD','TWD','EUR'].map(x=>`<option ${x===s.default_currency?'selected':''}>${x}</option>`).join('')}</select></label><label>Timezone<input name="timezone" value="${esc(s.timezone)}"></label><label>Notification email<input type="email" name="notification_email" value="${esc(s.notification_email)}"></label><label class="wide">Email sender<input type="email" name="email_sender" value="${esc(s.email_sender)}"></label></div><div class="form-actions"><button class="primary">Save settings</button></div></form></section><section class="card"><h2>Email delivery</h2><p class="notice">${d.emailDeliveryAvailable?'Amazon SES delivery is enabled. Queued messages will be sent by the backend.':'Queue only. Amazon SES delivery is not enabled, so no message will be sent.'}</p><h2 style="margin-top:28px">Pipeline stages</h2>${list(d.stages,x=>`<b>${esc(x.name)}</b><small>Position ${x.position}</small>`,x=>`${x.probability}%`)}</section></div>`;$('#settings-form').onsubmit=async e=>{e.preventDefault();await api('/api/settings',{method:'PATCH',body:JSON.stringify(Object.fromEntries(new FormData(e.target)))});toast('Settings saved')}}

const RENDER={dashboard,today:()=>taskView('today'),week:()=>taskView('week'),calendar,contacts:()=>resourceList('contacts'),companies:()=>resourceList('companies'),deals:()=>resourceList('deals'),pipeline,tasks:()=>taskView('all'),submissions,emails:()=>emails('all'),sent:()=>emails('sent'),compose:()=>resourceForm('emails',null,{status:'queued'}),audit:auditView,settings};
async function enterApp(){const session=await api('/api/session');$('#login').classList.add('hidden');$('#app').classList.remove('hidden');$('#user-name').textContent=session.user?.name||'CRM user';$('#user-role').textContent=session.user?.role||'Administrator';route((location.hash.slice(1) in RENDER)?location.hash.slice(1):'dashboard')}
$('#nav').innerHTML=nav();$('#nav').onclick=e=>{const b=e.target.closest('[data-route]');if(b){route(b.dataset.route);$('.sidebar').classList.remove('open')}};$('#drawer-backdrop').onclick=e=>{if(e.target.id==='drawer-backdrop')closeDrawer()};$('#menu').onclick=()=>$('.sidebar').classList.toggle('open');$('#refresh').onclick=()=>route(current);$('#signout').onclick=async()=>{try{await api('/api/logout',{method:'POST'})}catch{}token='';refreshToken='';sessionStorage.removeItem('thermoCrmAccessToken');sessionStorage.removeItem('thermoCrmRefreshToken');location.reload()};$('#quick-add').onclick=()=>resourceForm(current==='companies'?'companies':current==='deals'||current==='pipeline'?'deals':current==='tasks'||current==='today'||current==='week'||current==='calendar'?'tasks':current==='emails'||current==='sent'||current==='compose'?'emails':'contacts');
$('#login-help').textContent=cognitoEnabled?'Use the email and password created in the ThermoVerse Cognito user pool.':'Use the local administrator email and password configured on the server.';
$('#login-form').onsubmit=async e=>{e.preventDefault();$('#login-error').textContent='';try{if(cognitoEnabled)await signIn($('#username').value,$('#password').value,$('#new-password').value);else await localSignIn($('#username').value,$('#password').value);await enterApp()}catch(err){$('#login-error').textContent=err.message}};
if(token)enterApp().catch(()=>{token='';sessionStorage.removeItem('thermoCrmAccessToken')});
window.addEventListener('hashchange',()=>{const id=location.hash.slice(1);if(token&&id in RENDER&&id!==current)route(id)});
